// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpwFz82a0UfMJrdJcD6FQ6irty6rXizsA',
    appId: '1:81778557189:web:2e64349453251661a8f76c',
    messagingSenderId: '81778557189',
    projectId: 'chat-3-5f95a',
    authDomain: 'chat-3-5f95a.firebaseapp.com',
    storageBucket: 'chat-3-5f95a.appspot.com',
    measurementId: 'G-QYSBTQ2ZQY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB374KbE5oesQQ0BRBrTGbb91rfpduNpNs',
    appId: '1:81778557189:android:ae9976224c1e0fd1a8f76c',
    messagingSenderId: '81778557189',
    projectId: 'chat-3-5f95a',
    storageBucket: 'chat-3-5f95a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDwkbxbawoBEUoFqXkgDQA71dZlnomaZY',
    appId: '1:81778557189:ios:cdf3e5d60fb927a8a8f76c',
    messagingSenderId: '81778557189',
    projectId: 'chat-3-5f95a',
    storageBucket: 'chat-3-5f95a.appspot.com',
    androidClientId: '81778557189-07qskjhrhfrc2bhn1pp3hhdc66hdcotn.apps.googleusercontent.com',
    iosClientId: '81778557189-sdndk183706fd3qstad1l9j99ufjer91.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDwkbxbawoBEUoFqXkgDQA71dZlnomaZY',
    appId: '1:81778557189:ios:607b2c7cdcb4ab0ca8f76c',
    messagingSenderId: '81778557189',
    projectId: 'chat-3-5f95a',
    storageBucket: 'chat-3-5f95a.appspot.com',
    androidClientId: '81778557189-07qskjhrhfrc2bhn1pp3hhdc66hdcotn.apps.googleusercontent.com',
    iosClientId: '81778557189-i6u8k5j4lon3g3vfu2a5bqvq08qjfbm1.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
